.DEFAULT_GOAL := help
SHELL := /bin/bash

help: ## Show this help
	@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

install: ## Sync the uv workspace (runtime deps only)
	uv sync --no-dev

install-dev: ## Sync the workspace with dev tooling
	uv sync

lock: ## Refresh uv.lock
	uv lock

test: ## Run the test suite
	uv run pytest -q

lint: ## Ruff check
	uv run ruff check .

format: ## Ruff format + import sort
	uv run ruff format .
	uv run ruff check --fix .

check: lint test ## Lint and test — what CI runs

# ── Strategy plugins ────────────────────────────────────────────────────
#
# __strategies__/ can hold more than one strategy repository, each its own
# checkout with its own lockfile. Their code is a mounted volume and needs no
# installing, but their *dependencies* do: the runner imports the strategies
# into its own process. STRATEGY names the subfolder to act on
# (__strategies__/<name>); leave it unset to sweep every checkout under
# __strategies__/ that has a pyproject.toml. strategy-mount installs each
# repo's deps, then runs strategy-audit against it and records the result —
# true or false — in STRATEGIES_MANIFEST, an auto-generated file that must
# exist before `make up`/`make start` will run, even if it lists nothing.
# strategy-requirements only freezes the entries marked true.
#
# Audit runs *after* install, not before: the commonest audit failure is a
# missing third-party import, which is exactly what installing fixes, so
# auditing a repo before its deps exist would mark it false for a reason the
# next line was about to correct.

STRATEGIES_DIR := __strategies__
STRATEGIES_MANIFEST := $(STRATEGIES_DIR)/strategies.toml
STRATEGY ?=

strategy-audit: ## Audit one mounted strategy repo; prints true or false to stdout (STRATEGY=<name> required)
	@if [ -z "$(STRATEGY)" ]; then \
		echo "STRATEGY is required, e.g. make strategy-audit STRATEGY=my-strategies" >&2; \
		exit 1; \
	fi; \
	repo="$(STRATEGIES_DIR)/$(STRATEGY)"; \
	if [ ! -d "$$repo" ]; then \
		echo "No such strategy folder: $$repo" >&2; \
		echo false; \
		exit 0; \
	fi; \
	if uv run qte-strategy-audit --dir "$$repo" --no-routing 1>&2; then \
		echo true; \
	else \
		echo false; \
	fi

strategy-mount: ## Install one (STRATEGY=<name>) or every mounted strategy repo's deps into this venv
	@set -e; \
	if [ -n "$(STRATEGY)" ]; then \
		names="$(STRATEGY)"; \
	else \
		names=$$(cd $(STRATEGIES_DIR) && for dir in */; do name=$${dir%/}; if [ -f "$$name/pyproject.toml" ]; then echo "$$name"; fi; done; true); \
	fi; \
	if [ -z "$$names" ]; then \
		echo "No strategy repos with a pyproject.toml under $(STRATEGIES_DIR)/"; \
	fi; \
	new_entries=$$(mktemp); \
	for name in $$names; do \
		repo="$(STRATEGIES_DIR)/$$name"; \
		[ -f "$$repo/pyproject.toml" ] || { echo "No pyproject.toml at $$repo"; exit 1; }; \
		echo "Mounting $$name"; \
		uv export --project "$$repo" --no-dev --no-emit-project \
			--format requirements-txt | uv pip install -r -; \
		passed=$$($(MAKE) --no-print-directory strategy-audit STRATEGY=$$name 2>/dev/null); \
		echo "Audit for $$name: $$passed"; \
		echo "$$name = $$passed" >> "$$new_entries"; \
	done; \
	kept=$$(mktemp); \
	if [ -n "$(STRATEGY)" ] && [ -f $(STRATEGIES_MANIFEST) ]; then \
		grep -E ' = (true|false)$$' $(STRATEGIES_MANIFEST) | grep -Ev "^$(STRATEGY) = " > "$$kept" || true; \
	fi; \
	{ printf '%s\n' \
		'# AUTO-GENERATED by `make strategy-mount` - do not hand-edit.' \
		'#' \
		'# Do not delete this file once it exists, even if it lists nothing below:' \
		'# `make strategy-requirements` reads it to decide what to freeze into' \
		'# deploy/, and `make up` / `make start` refuse to start the stack without' \
		'# it. Re-run `make strategy-mount` (optionally with STRATEGY=<name>) to' \
		'# refresh it. true means that repo passed `make strategy-audit` the last' \
		'# time it was mounted; false entries are skipped by strategy-requirements.' \
		''; \
	  echo '[strategies]'; \
	  cat "$$kept" "$$new_entries" | sort -u; \
	} > $(STRATEGIES_MANIFEST).tmp && mv $(STRATEGIES_MANIFEST).tmp $(STRATEGIES_MANIFEST); \
	rm -f "$$new_entries" "$$kept"; \
	echo "Recorded $$(grep -cE ' = (true|false)$$' $(STRATEGIES_MANIFEST)) strategy repo(s) in $(STRATEGIES_MANIFEST), $$(grep -c ' = true$$' $(STRATEGIES_MANIFEST)) passing audit"

strategy-requirements: ## Freeze deps for one (STRATEGY=<name>) or every mounted repo (from STRATEGIES_MANIFEST) into deploy/
	@set -e; \
	if [ -n "$(STRATEGY)" ]; then \
		names="$(STRATEGY)"; \
	else \
		if [ ! -f $(STRATEGIES_MANIFEST) ]; then \
			echo "$(STRATEGIES_MANIFEST) is missing - run 'make strategy-mount' first (even with no repos to mount, it must exist)"; \
			exit 1; \
		fi; \
		names=$$(grep -E ' = true$$' $(STRATEGIES_MANIFEST) | sed -E 's/ = true$$//'); \
	fi; \
	if [ -z "$$names" ]; then \
		echo "No mounted strategy repos listed in $(STRATEGIES_MANIFEST) - nothing to freeze"; \
		: > deploy/strategy-requirements.txt; \
		exit 0; \
	fi; \
	tmp=$$(mktemp); \
	for name in $$names; do \
		repo="$(STRATEGIES_DIR)/$$name"; \
		if [ -f "$$repo/pyproject.toml" ]; then \
			uv export --project "$$repo" --no-dev --no-emit-project \
				--format requirements-txt >> "$$tmp"; \
		else \
			echo "No strategy repo at $$repo - skipping"; \
		fi; \
	done; \
	mv "$$tmp" deploy/strategy-requirements.txt; \
	echo "Wrote deploy/strategy-requirements.txt from: $$names"

strategy-test: ## Run one mounted strategy repo's own suite (STRATEGY=<name> required)
	@if [ -z "$(STRATEGY)" ]; then \
		echo "STRATEGY is required, e.g. make strategy-test STRATEGY=my-strategies"; \
		exit 1; \
	fi
	$(MAKE) -C $(STRATEGIES_DIR)/$(STRATEGY) check

audit: ## Validate __strategies__/ against the QTE signal contract + routing table
	uv run qte-strategy-audit

audit-strict: ## Same, but warnings fail too — what CI should run
	uv run qte-strategy-audit --strict

strategy-mapping: ## Copy the strategies-mapping template into place (never overwrites)
	@if [ -f config/strategies_mapping.toml ]; then \
		echo "config/strategies_mapping.toml exists - leaving it alone"; \
	else \
		cp config/strategies_mapping.example.toml config/strategies_mapping.toml; \
		echo "Wrote config/strategies_mapping.toml (git-ignored) - pair your symbols with strategies in it"; \
	fi

strategies: ## List what the mounted strategy repo publishes
	uv run python -c "from qte_shared.config import settings; \
		from qte_shared.plugin_loader import load_strategies; \
		[print(e.name, 'from', e.source) for e in load_strategies(settings.engine.strategies_dir)]"

infra: ## Start redis, postgres and nats only
	docker compose up -d redis-cache postgres-audit nats

up: strategy-requirements ## Start the whole stack
	docker compose up -d --build

start: strategy-requirements ## `up` + wait for db-migrate to finish; the local dev entry point
	docker compose up -d --build
	@echo "Stack is up. Data-ingestion / strategy-runner block until db-migrate exits 0."
	@echo "Drive the simulator with: make bar O=2400 H=2412.5 L=2396.25 C=2408.75"

stop: ## Stop the stack (volumes survive) — alias of `down`
	docker compose down

down: ## Stop the stack (volumes survive)
	docker compose down

restart: ## Recreate every app container (keeps volumes and infra)
	docker compose up -d --build --force-recreate data-ingestion strategy-runner market-simulator

logs: ## Tail every service
	docker compose logs -f --tail=100

nuke: ## Stop the stack and DELETE its volumes (audit trail included)
	docker compose down -v

db-upgrade: ## Apply every pending migration
	uv run alembic upgrade head

db-downgrade: ## Roll back one migration
	uv run alembic downgrade -1

db-revision: ## Autogenerate a migration from model changes: make db-revision M="add x"
	uv run alembic revision --autogenerate -m "$(M)"

db-current: ## Which revision the database is on
	uv run alembic current --verbose

db-history: ## The migration history
	uv run alembic history --indicate-current

db-check: ## Fail if the models have drifted from the migrations
	uv run alembic check

csv-import: ## Convert an MT5 CSV export to parquet: make csv-import CSV=data/csv/x.csv [TZ=EET] [ARGS=--overwrite]
	uv run python scripts/mt5_csv_to_parquet.py $(CSV) --tz $(or $(TZ),UTC) $(ARGS)

download: ## Fetch provider history for QTE_ENGINE__SYMBOLS into parquet
	uv run qte-backtest download

history: ## List the parquet history on disk
	uv run qte-backtest list

backtest: ## Replay one strategy: make backtest STRATEGY=... SYMBOL=XAUUSD [TF=M15]
	uv run qte-backtest run --strategy $(STRATEGY) --symbol $(SYMBOL) \
		--timeframe $(or $(TF),M15) --report

chart: ## Draw a report as an interactive HTML dashboard: make chart REPORT=data/reports/x.json
	uv run qte-backtest chart $(REPORT)

reports: ## List the backtest reports written so far
	@ls -lht data/reports 2>/dev/null | head -20 || echo "No reports yet — run make backtest"

ingestion: ## Run the ingestion service locally
	uv run qte-ingestion

runner: ## Run the strategy runner locally
	uv run qte-strategy-runner

# ── Dev market data simulator ───────────────────────────────────────────
#
# A WebSocket feed you drive by hand, so the whole pipeline can be rehearsed
# without a market being open. Refuses to run unless QTE_ENV=dev. The full
# walkthrough is docs/simulator.md.

SIM_SYMBOL ?= XAUUSD
SIM_TF     ?= M15
SIM_BARS   ?= 300
# Where a successful vendor fetch parks its bars. `warmup-cache` replays these
# into the simulator, so a dev stack rehearses on prices that really printed
# without spending a request against a rate-limited plan.
HISTORY_CACHE ?= data/parquet/tiingo
# Bars replayed by `warmup-cache`. Defaults to the Redis retention so one run
# fills the window the runner will actually read.
CACHE_BARS ?= 6000

sim: ## Run the dev websocket market data simulator (QTE_ENV=dev only)
	uv run qte-simulator serve

sim-up: ## (Re)build and start just the market-simulator container
	docker compose up -d --build market-simulator

sim-status: ## What the simulator is doing, and who is attached to it
	uv run qte-simulator status

warmup-cache: ## Warm the engine from real cached bars: make warmup-cache [CACHE_BARS=6000]
	uv run qte-simulator replay --symbol $(SIM_SYMBOL) --timeframe $(SIM_TF) \
		--file $(HISTORY_CACHE)/$(SIM_SYMBOL)_$(SIM_TF).parquet \
		--limit $(CACHE_BARS) --verify

sim-replay warmup: ## Warm the engine with synthetic bars: make warmup [SIM_BARS=300]
	uv run qte-simulator replay --symbol $(SIM_SYMBOL) --timeframe $(SIM_TF) \
		--generate $(SIM_BARS) --seed 7 --verify

sim-bar bar: ## One bar, round-tripped: make bar O=2400 H=2412.5 L=2396.25 C=2408.75 [V=150]
	uv run qte-simulator bar --symbol $(SIM_SYMBOL) --timeframe $(SIM_TF) \
		--open $(O) --high $(H) --low $(L) --close $(C) \
		$(if $(V),--volume $(V),) --verify

signal: ## Warmup + drift replay expected to fire a signal (fails if none does)
	uv run qte-simulator replay --symbol $(SIM_SYMBOL) --timeframe $(SIM_TF) \
		--generate $(SIM_BARS) --seed 7 --verify
	uv run qte-simulator replay --symbol $(SIM_SYMBOL) --timeframe $(SIM_TF) \
		--generate 60 --seed 3 --drift 0.004 --volatility 0.0015 \
		--verify --expect-signal

sim-walk: ## Stream a live-ish random walk until stopped
	uv run qte-simulator walk --symbol $(SIM_SYMBOL) --rate 5

sim-stop: ## Stop every background generator
	uv run qte-simulator stop

sim-reset: ## Clear Redis + reset the simulator cursor + restart ingestion (fixes 'no candle arrived')
	-uv run qte-simulator stop
	-uv run qte-simulator reset
	docker compose exec -T redis-cache redis-cli FLUSHDB
	docker compose restart data-ingestion strategy-runner

sim-watch: ## Tail closed candles and emitted signals on NATS
	uv run qte-simulator watch --symbol $(SIM_SYMBOL) --timeframe $(SIM_TF)

shadow-status: ## Show whether signals are reaching the broker
	uv run qte-control shadow status

shadow-on: ## Pause delivery to the broker on every running runner
	uv run qte-control shadow on

shadow-off: ## Resume delivery to the broker (GOES LIVE — prompts to confirm)
	uv run qte-control shadow off

ping: ## Ask the running runners to identify themselves
	uv run qte-control ping

.PHONY: help install install-dev lock test lint format check infra up start stop down restart logs nuke \
	strategy-mount strategy-audit strategy-requirements strategy-test strategies audit audit-strict strategy-mapping \
	db-upgrade db-downgrade db-revision db-current db-history db-check \
	download history backtest chart reports ingestion runner csv-import \
	sim sim-up sim-status sim-replay warmup warmup-cache sim-bar bar signal sim-walk sim-stop sim-reset sim-watch \
	shadow-status shadow-on shadow-off ping
