.DEFAULT_GOAL := help
SHELL := /bin/bash

help: ## Show this help, grouped by section
	@awk 'BEGIN {FS = ":.*?## "} \
		/^##@ / {printf "\n\033[1m%s\033[0m\n", substr($$0, 5); next} \
		/^[a-zA-Z0-9_-]+([ ]+[a-zA-Z0-9_-]+)*:.*?## / \
		{split($$1, names, " "); printf "  \033[36m%-20s\033[0m %s\n", names[1], $$2}' \
		$(MAKEFILE_LIST)
	@echo

##@ Project

# --all-extras locally: one venv has to run every entry point, including
# `make backtest` (pyarrow) and `make simulator` (websockets). The images are
# the place where extras get selected, not the developer's machine.
install: ## Sync the environment (runtime deps only)
	uv sync --no-dev --all-extras

install-dev: ## Sync the environment with dev tooling
	uv sync --all-extras

lock: ## Refresh uv.lock
	uv lock

##@ Quality

test: ## Run the test suite
	uv run pytest -q

lint: ## Ruff check
	uv run ruff check .

format: ## Ruff format + import sort
	uv run ruff format .
	uv run ruff check --fix .

check: lint test ## Lint and test — what CI runs

##@ Strategies

# ── Strategy plugins ────────────────────────────────────────────────────
#
# __strategies__/ can hold more than one strategy repository, each its own
# checkout with its own lockfile. Their code is a mounted volume and needs no
# installing, but their *dependencies* do: the runner imports the strategies
# into its own process. STRATEGY names the subfolder to act on
# (__strategies__/<name>); leave it unset to sweep every checkout under
# __strategies__/ that has a pyproject.toml. strategy-mount installs each
# repo's deps, then runs strategy-audit against it and records the result —
# true or false — in STRATEGIES_MANIFEST, an auto-generated file that must
# exist before `make up`/`make start` will run, even if it lists nothing.
# strategy-requirements only freezes the entries marked true.
#
# Audit runs *after* install, not before: the commonest audit failure is a
# missing third-party import, which is exactly what installing fixes, so
# auditing a repo before its deps exist would mark it false for a reason the
# next line was about to correct.

STRATEGIES_DIR := __strategies__
STRATEGIES_MANIFEST := $(STRATEGIES_DIR)/strategies.toml
STRATEGY ?=

strategy-audit: ## Audit one mounted strategy repo; prints true or false to stdout (STRATEGY=<name> required)
	@if [ -z "$(STRATEGY)" ]; then \
		echo "STRATEGY is required, e.g. make strategy-audit STRATEGY=my-strategies" >&2; \
		exit 1; \
	fi; \
	repo="$(STRATEGIES_DIR)/$(STRATEGY)"; \
	if [ ! -d "$$repo" ]; then \
		echo "No such strategy folder: $$repo" >&2; \
		echo false; \
		exit 0; \
	fi; \
	if uv run qte-strategy-audit --dir "$$repo" --no-mapping 1>&2; then \
		echo true; \
	else \
		echo false; \
	fi

strategy-mount: ## Install one (STRATEGY=<name>) or every mounted strategy repo's deps into this venv
	@set -e; \
	if [ -n "$(STRATEGY)" ]; then \
		names="$(STRATEGY)"; \
	else \
		names=$$(cd $(STRATEGIES_DIR) && for dir in */; do name=$${dir%/}; if [ -f "$$name/pyproject.toml" ]; then echo "$$name"; fi; done; true); \
	fi; \
	if [ -z "$$names" ]; then \
		echo "No strategy repos with a pyproject.toml under $(STRATEGIES_DIR)/"; \
	fi; \
	new_entries=$$(mktemp); \
	for name in $$names; do \
		repo="$(STRATEGIES_DIR)/$$name"; \
		[ -f "$$repo/pyproject.toml" ] || { echo "No pyproject.toml at $$repo"; exit 1; }; \
		echo "Mounting $$name"; \
		uv export --project "$$repo" --no-dev --no-emit-project \
			--format requirements-txt | uv pip install -r -; \
		passed=$$($(MAKE) --no-print-directory strategy-audit STRATEGY=$$name 2>/dev/null); \
		echo "Audit for $$name: $$passed"; \
		echo "$$name = $$passed" >> "$$new_entries"; \
	done; \
	kept=$$(mktemp); \
	if [ -n "$(STRATEGY)" ] && [ -f $(STRATEGIES_MANIFEST) ]; then \
		grep -E ' = (true|false)$$' $(STRATEGIES_MANIFEST) | grep -Ev "^$(STRATEGY) = " > "$$kept" || true; \
	fi; \
	{ printf '%s\n' \
		'# AUTO-GENERATED by `make strategy-mount` - do not hand-edit.' \
		'#' \
		'# Do not delete this file once it exists, even if it lists nothing below:' \
		'# `make strategy-requirements` reads it to decide what to freeze into' \
		'# deploy/, and `make up` / `make start` refuse to start the stack without' \
		'# it. Re-run `make strategy-mount` (optionally with STRATEGY=<name>) to' \
		'# refresh it. true means that repo passed `make strategy-audit` the last' \
		'# time it was mounted; false entries are skipped by strategy-requirements.' \
		''; \
	  echo '[strategies]'; \
	  cat "$$kept" "$$new_entries" | sort -u; \
	} > $(STRATEGIES_MANIFEST).tmp && mv $(STRATEGIES_MANIFEST).tmp $(STRATEGIES_MANIFEST); \
	rm -f "$$new_entries" "$$kept"; \
	echo "Recorded $$(grep -cE ' = (true|false)$$' $(STRATEGIES_MANIFEST)) strategy repo(s) in $(STRATEGIES_MANIFEST), $$(grep -c ' = true$$' $(STRATEGIES_MANIFEST)) passing audit"

strategy-requirements: ## Freeze deps for one (STRATEGY=<name>) or every mounted repo (from STRATEGIES_MANIFEST) into deploy/
	@set -e; \
	if [ -n "$(STRATEGY)" ]; then \
		names="$(STRATEGY)"; \
	else \
		if [ ! -f $(STRATEGIES_MANIFEST) ]; then \
			echo "$(STRATEGIES_MANIFEST) is missing - run 'make strategy-mount' first (even with no repos to mount, it must exist)"; \
			exit 1; \
		fi; \
		names=$$(grep -E ' = true$$' $(STRATEGIES_MANIFEST) | sed -E 's/ = true$$//'); \
	fi; \
	if [ -z "$$names" ]; then \
		echo "No mounted strategy repos listed in $(STRATEGIES_MANIFEST) - nothing to freeze"; \
		: > deploy/strategy-requirements.txt; \
		exit 0; \
	fi; \
	tmp=$$(mktemp); \
	for name in $$names; do \
		repo="$(STRATEGIES_DIR)/$$name"; \
		if [ -f "$$repo/pyproject.toml" ]; then \
			uv export --project "$$repo" --no-dev --no-emit-project \
				--format requirements-txt >> "$$tmp"; \
		else \
			echo "No strategy repo at $$repo - skipping"; \
		fi; \
	done; \
	mv "$$tmp" deploy/strategy-requirements.txt; \
	echo "Wrote deploy/strategy-requirements.txt from: $$names"

strategy-test: ## Run one mounted strategy repo's own suite (STRATEGY=<name> required)
	@if [ -z "$(STRATEGY)" ]; then \
		echo "STRATEGY is required, e.g. make strategy-test STRATEGY=my-strategies"; \
		exit 1; \
	fi
	$(MAKE) -C $(STRATEGIES_DIR)/$(STRATEGY) check

audit: ## Validate __strategies__/ against the QTE signal contract + mapping table
	uv run qte-strategy-audit

audit-strict: ## Same, but warnings fail too — what CI should run
	uv run qte-strategy-audit --strict

strategy-mapping: ## Copy the strategies-mapping template into place (never overwrites)
	@if [ -f config/strategies_mapping.toml ]; then \
		echo "config/strategies_mapping.toml exists - leaving it alone"; \
	else \
		cp config/strategies_mapping.example.toml config/strategies_mapping.toml; \
		echo "Wrote config/strategies_mapping.toml (git-ignored) - pair your symbols with strategies in it"; \
	fi

strategies: ## List what the mounted strategy repo publishes
	uv run python -c "from qte_shared.config import settings; \
		from qte_shared.plugin_loader import load_strategies; \
		[print(e.name, 'from', e.source) for e in load_strategies(settings.engine.strategies_dir)]"

##@ Market data

# What a provider is asked to feed — symbols, their markets and timeframes, and
# the vendor's own knobs — lives in config/<provider>.toml, not in .env: it is a
# per-symbol matrix and the flat form could not express one. The real file is
# git-ignored like the mapping table; the template beside it is tracked.
# The key is the exception and stays in .env as QTE_DATA_PROVIDER_API_KEY.

tiingo: ## Copy the Tiingo market-data plan into place (never overwrites)
	@if [ -f config/tiingo.toml ]; then \
		echo "config/tiingo.toml exists - leaving it alone"; \
	else \
		cp config/tiingo.example.toml config/tiingo.toml; \
		echo "Wrote config/tiingo.toml (git-ignored) - list the symbols you want fed in it"; \
	fi

# Guards `up` and `start`. A missing plan does not fail at runtime: the engine
# falls back to the QTE_ENGINE__* defaults and quietly subscribes to something
# nobody asked for, which on a live vendor is the wrong kind of surprise. The
# simulator is exempt — it is the one provider with no plan and no key.
market-plan: ## Fail unless the configured provider has its plan file
	@provider=$$(sed -n 's/^QTE_MARKET_DATA__PROVIDER=//p' .env 2>/dev/null | tail -n1 | tr -d '"' | tr -d "\r' "); \
	plan=$$(sed -n 's/^QTE_MARKET_DATA__CONFIG_FILE=//p' .env 2>/dev/null | tail -n1 | tr -d '"' | tr -d "\r' "); \
	[ -n "$$provider" ] || provider=tiingo; \
	[ -n "$$plan" ] || plan="config/$$provider.toml"; \
	if [ "$$provider" = "simulator" ]; then exit 0; fi; \
	if [ ! -f "$$plan" ]; then \
		echo "QTE_MARKET_DATA__PROVIDER=$$provider, but $$plan does not exist." >&2; \
		echo "Without it the engine falls back to the QTE_ENGINE__* defaults and" >&2; \
		echo "subscribes to symbols nobody chose." >&2; \
		if [ -f "config/$$provider.example.toml" ]; then \
			echo "Write one:  make $$provider" >&2; \
		else \
			echo "There is no config/$$provider.example.toml to copy - write $$plan by hand." >&2; \
		fi; \
		exit 1; \
	fi; \
	echo "Market-data plan: $$plan"

##@ Stack

up: market-plan strategy-requirements ## Start the whole stack
	docker compose up -d --build

start: market-plan strategy-requirements ## `up` + wait for db-migrate to finish; the local dev entry point
	docker compose up -d --build
	@echo "Stack is up. Data-ingestion / strategy-runner block until db-migrate exits 0."
	@echo "Drive the simulator with: make bar O=2400 H=2412.5 L=2396.25 C=2408.75"

stop: ## Stop the stack (volumes survive) — alias of `down`
	docker compose down

down: ## Stop the stack (volumes survive)
	docker compose down

restart: ## Recreate every app container (keeps volumes and infra)
	docker compose up -d --build --force-recreate data-ingestion strategy-runner market-simulator

# ── Live-editing dev loop ──────────────────────────────────────────────
#
# `make dev` is `start` with the workspace source bind-mounted over the copy in
# the image (docker-compose.dev.yml). Build it once; after that a code edit is
# live in the container, so the loop is: edit -> `make dev-restart` (seconds,
# no rebuild) -> `make logs`. A dependency change still needs `make dev` again.

DEV_COMPOSE := -f docker-compose.yml -f docker-compose.dev.yml

dev: market-plan strategy-requirements ## `start` with src/ bind-mounted for live editing
	docker compose $(DEV_COMPOSE) up -d --build

dev-restart: ## Reload code after an edit — restart the app processes, no rebuild
	docker compose $(DEV_COMPOSE) restart data-ingestion strategy-runner market-simulator

logs: ## Tail every service
	docker compose logs -f --tail=100

nuke: ## Stop the stack and DELETE its volumes (audit trail included)
	docker compose down -v

##@ Database

db-upgrade: ## Apply every pending migration
	uv run alembic upgrade head

db-downgrade: ## Roll back one migration
	uv run alembic downgrade -1

db-revision: ## Autogenerate a migration from model changes: make db-revision M="add x"
	uv run alembic revision --autogenerate -m "$(M)"

db-current: ## Which revision the database is on
	uv run alembic current --verbose

db-history: ## The migration history
	uv run alembic history --indicate-current

db-check: ## Fail if the models have drifted from the migrations
	uv run alembic check

##@ History and backtests

csv-import: ## Convert an MT5 CSV export to parquet: make csv-import CSV=data/csv/x.csv [TZ=EET] [ARGS=--overwrite]
	uv run python scripts/mt5_csv_to_parquet.py $(CSV) --tz $(or $(TZ),UTC) $(ARGS)

download: ## Fetch provider history for every symbol in the market-data plan
	uv run qte-backtest download

history: ## List the parquet history on disk
	uv run qte-backtest list

backtest: ## Replay one strategy: make backtest STRATEGY=... SYMBOL=XAUUSD [TF=M15]
	uv run qte-backtest run --strategy $(STRATEGY) --symbol $(SYMBOL) \
		--timeframe $(or $(TF),M15) --report

chart: ## Draw a report as an interactive HTML dashboard: make chart REPORT=data/reports/x.json
	uv run qte-backtest chart $(REPORT)

reports: ## List the backtest reports written so far
	@ls -lht data/reports 2>/dev/null | head -20 || echo "No reports yet — run make backtest"

##@ Run a service locally

ingestion: ## Run the ingestion service locally
	uv run qte-ingestion

runner: ## Run the strategy runner locally
	uv run qte-strategy-runner

##@ Simulator

# ── Dev market data simulator ───────────────────────────────────────────
#
# A WebSocket feed you drive by hand, so the whole pipeline can be rehearsed
# without a market being open. Refuses to run unless QTE_ENV=dev. The full
# walkthrough is docs/simulator.md.

# These targets carry no parameters of their own. The symbol, the timeframe,
# the bar counts and the cached history file all come from .env — the same file
# ingestion and the runner read — so a rehearsal cannot aim at a symbol the
# engine is not watching or a window the runner will not keep:
#
#   QTE_ENGINE__SYMBOLS            the symbol, first entry
#   QTE_ENGINE__SIGNAL_TIMEFRAME   the timeframe
#   QTE_SIMULATOR__GENERATE_BARS   synthetic bars for `make warmup`
#   QTE_SIMULATOR_PARQUET_FILE     the vendor parquet `make warmup-cache` plays
#   QTE_SIMULATOR__CACHE_BARS      how many of its trailing bars
#
# For a one-off, pass the flag instead of editing .env:
#   uv run qte-simulator replay --generate 500 --seed 7

sim: ## Run the dev websocket market data simulator (QTE_ENV=dev only)
	uv run qte-simulator serve

sim-status: ## What the simulator is doing, and who is attached to it
	uv run qte-simulator status

# No --verify here, unlike the synthetic warm-up: real history is anchored in
# the past, where ingestion's wall-clock flush can close a bar between two of
# its own ticks. That costs about one bar per flush interval the replay lasts —
# fine for a warm-up window, and a guaranteed red for a bar-by-bar check.
warmup-cache: ## Warm the engine from the cached vendor parquet (QTE_SIMULATOR_PARQUET_FILE)
	uv run qte-simulator replay

warmup sim-replay: ## Warm the engine with synthetic bars (QTE_SIMULATOR__GENERATE_BARS)
	uv run qte-simulator replay --generate --seed 7 --verify

bar sim-bar: ## One bar, round-tripped: make bar O=2400 H=2412.5 L=2396.25 C=2408.75 [V=150]
	uv run qte-simulator bar --open $(O) --high $(H) --low $(L) --close $(C) \
		$(if $(V),--volume $(V),) --verify

signal: ## Warmup + drift replay expected to fire a signal (fails if none does)
	uv run qte-simulator replay --generate --seed 7 --verify
	uv run qte-simulator replay --generate 60 --seed 3 --drift 0.004 \
		--volatility 0.0015 --verify --expect-signal

sim-walk: ## Stream a live-ish random walk until stopped
	uv run qte-simulator walk --rate 5

sim-stop: ## Stop every background generator
	uv run qte-simulator stop

sim-reset: ## Clear Redis + reset the simulator cursor + restart ingestion (fixes 'no candle arrived')
	-uv run qte-simulator stop
	-uv run qte-simulator reset
	docker compose exec -T redis-cache redis-cli FLUSHDB
	docker compose restart data-ingestion strategy-runner

sim-watch: ## Tail closed candles and emitted signals on NATS
	uv run qte-simulator watch

##@ Live control

shadow-status: ## Show whether signals are reaching the broker
	uv run qte-control shadow status

shadow-on: ## Pause delivery to the broker on every running runner
	uv run qte-control shadow on

shadow-off: ## Resume delivery to the broker (GOES LIVE — prompts to confirm)
	uv run qte-control shadow off

ping: ## Ask the running runners to identify themselves
	uv run qte-control ping

.PHONY: help install install-dev lock test lint format check tiingo market-plan \
	up start stop down restart dev dev-restart logs nuke \
	strategy-mount strategy-audit strategy-requirements strategy-test strategies audit audit-strict strategy-mapping \
	db-upgrade db-downgrade db-revision db-current db-history db-check \
	download history backtest chart reports ingestion runner csv-import \
	sim sim-status sim-replay warmup warmup-cache sim-bar bar signal sim-walk sim-stop sim-reset sim-watch \
	shadow-status shadow-on shadow-off ping
