"""What ``make strategy-mount`` recorded about the strategies it mounted.

``__strategies__/strategies.toml`` is generated, never hand-edited, and read by
two consumers that want different things from it:

* ``make strategy-requirements`` freezes into ``deploy/`` the dependencies of
  every repository that still has something worth running.
* :mod:`qte_shared.strategies.plugin_loader` skips what the mount recorded as
  failing, so a strategy whose dependencies were never frozen is not imported
  and traded inside an image that lacks them.

Both need the same two levels, which is the shape of the file::

    [strategies._boilerplate]
    QTE_BOILERPLATE_M15 = true

    [strategies.quant-trading-strategies]
    MT5_GOLD_M15_V1 = true
    MT5_GOLD_M5_V1 = false

One table per mounted repository — because dependencies are frozen per
repository, and that is the unit a clone arrives in — and one key per strategy
that repository publishes, because that is the unit that trades. The value is
whether *that strategy* passed ``qte-strategy-audit`` the last time the repo
was mounted. A repository publishing nothing keeps an empty table rather than
disappearing, so "mounted and publishes nothing" stays distinguishable from
"never mounted".

A malformed file raises here rather than being guessed at. The two consumers
disagree about what to do next — the deploy step should stop, the trading
process should not — so that decision belongs to them, not to the parser.
"""

from __future__ import annotations

import json
import re
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

#: Written beside the repositories it describes, inside the strategies
#: directory, so moving or remounting that directory carries its record with it.
MOUNT_MANIFEST_FILENAME = "strategies.toml"

#: The single top-level table, holding one sub-table per mounted repository.
MOUNT_MANIFEST_TABLE = "strategies"

#: Keys TOML accepts unquoted. Anything else is quoted on the way out.
BARE_KEY = re.compile(r"^[A-Za-z0-9_-]+$")

MANIFEST_HEADER = """# AUTO-GENERATED by `make strategy-mount` - do not hand-edit.
#
# One table per mounted repository, one key per strategy it publishes, and the
# value is whether that strategy passed `qte-strategy-audit` the last time the
# repo was mounted.
#
# Do not delete this file once it exists, even if it lists nothing below:
# `make strategy-requirements` reads it to decide whose dependencies to freeze
# into deploy/, the strategy runner reads it to decide what it may load, and
# `make up` / `make start` refuse to start the stack without it.
#
# A strategy marked false is frozen into no image and loaded by no engine. Fix
# what the audit reported, then re-run `make strategy-mount` (optionally with
# STRATEGY=<name>) to refresh this file.
"""


@dataclass(frozen=True, slots=True)
class MountManifest:
    """The mount record: repository name to {strategy alias: passed the audit}."""

    repositories: dict[str, dict[str, bool]] = field(default_factory=dict)
    #: The file this was read from, or ``None`` when nothing was on disk.
    source: Path | None = None

    # ── Reading ───────────────────────────────────────────────────────

    @staticmethod
    def path_in(directory: Path | str) -> Path:
        return Path(directory) / MOUNT_MANIFEST_FILENAME

    @classmethod
    def load(cls, directory: Path | str) -> MountManifest:
        """Parse the manifest in *directory*, or return an empty one.

        A missing file is not an error: the mount step has simply not run yet,
        or the directory holds loose strategy files rather than cloned
        repositories. A file that will not parse — or that carries the flat
        ``<repo> = true`` shape this format replaced — raises
        :class:`ValueError`, naming the fix.
        """
        path = cls.path_in(directory)
        if not path.is_file():
            return cls()

        try:
            with path.open("rb") as handle:
                document = tomllib.load(handle)
        except tomllib.TOMLDecodeError as error:
            # tomllib names the syntax but never the file, and the caller only
            # ever holds a directory. Which file is half the answer.
            raise ValueError(f"{path}: {error}") from error

        table = document.get(MOUNT_MANIFEST_TABLE, {})
        if not isinstance(table, dict):
            raise ValueError(f"{path}: [{MOUNT_MANIFEST_TABLE}] must be a table of repositories")

        repositories: dict[str, dict[str, bool]] = {}
        for repository, published in table.items():
            if not isinstance(published, dict):
                # ASCII: this lands on an operator's Windows console as often
                # as in a container, and the report next to it is ASCII for the
                # same reason.
                raise ValueError(
                    f"{path}: [{MOUNT_MANIFEST_TABLE}.{repository}] must be a table of "
                    "strategy names, not one verdict for the whole repository. This file "
                    "predates per-strategy records - re-run `make strategy-mount`."
                )
            repositories[str(repository)] = {
                str(alias): bool(passed) for alias, passed in published.items()
            }
        return cls(repositories=repositories, source=path)

    # ── What the consumers ask it ─────────────────────────────────────

    @property
    def verdicts(self) -> dict[str, bool]:
        """Every recorded strategy, flattened out of its repository."""
        return {
            alias: passed
            for published in self.repositories.values()
            for alias, passed in published.items()
        }

    @property
    def disabled_strategies(self) -> frozenset[str]:
        """Strategy names recorded as having failed their audit."""
        return frozenset(alias for alias, passed in self.verdicts.items() if not passed)

    @property
    def disabled_repositories(self) -> frozenset[str]:
        """Repositories with nothing left worth importing.

        Every strategy they publish failed, so there is no reason to put the
        repo on ``sys.path`` at all. A repository recorded as publishing
        nothing is not one of these: it may have grown a strategy since, and
        that one is unrecorded rather than rejected.
        """
        return frozenset(
            repository
            for repository, published in self.repositories.items()
            if published and not any(published.values())
        )

    @property
    def passing_repositories(self) -> tuple[str, ...]:
        """Repositories whose dependencies still have to reach the image."""
        return tuple(
            sorted(
                repository
                for repository, published in self.repositories.items()
                if any(published.values())
            )
        )

    # ── Writing ───────────────────────────────────────────────────────

    def with_repository(self, repository: str, verdicts: dict[str, bool]) -> MountManifest:
        """This manifest with one repository's record replaced wholesale.

        Replaced rather than merged: a strategy the repo no longer publishes
        has to leave the file, or a rename would keep granting the old name a
        pass nothing re-audited it for.
        """
        updated = dict(self.repositories)
        updated[repository] = {alias: bool(passed) for alias, passed in verdicts.items()}
        return MountManifest(repositories=updated, source=self.source)

    def render(self) -> str:
        """The file's text, repositories and strategies both in sorted order.

        Sorted so remounting an unchanged directory produces a byte-identical
        file, and a diff only ever shows a verdict that actually moved.
        """
        lines = [MANIFEST_HEADER]
        for repository in sorted(self.repositories):
            lines.append(f"[{MOUNT_MANIFEST_TABLE}.{_toml_key(repository)}]")
            published = self.repositories[repository]
            for alias in sorted(published):
                lines.append(f"{_toml_key(alias)} = {str(published[alias]).lower()}")
            lines.append("")
        return "\n".join(lines)

    def write(self, directory: Path | str) -> Path:
        """Render into ``<directory>/strategies.toml``, replacing what is there."""
        path = self.path_in(directory)
        path.write_text(self.render(), encoding="utf-8")
        return path


def _toml_key(name: str) -> str:
    """A bare key where TOML allows one, a quoted key where it does not.

    TOML basic strings take the same escapes JSON does for everything a
    directory or alias can realistically contain, so the quoting is delegated
    rather than hand-rolled.
    """
    if BARE_KEY.match(name):
        return name
    return json.dumps(name)
